### ISSUE TITLE
Can you add FactionsOne support?

### ISSUE THREAD

**Issue by Scuffi** [JCulley/ProQuests-Documentation#10]
Hi, I use FactionsOne and I really want to use the FACTION quests. If you could support FactionsOne in ProQuests it would be greatly appreciated. 

Thank you.

**Comment by JCulley** [comment]
As stated in the guidelines if it is related to a specific plugin I ask you please provide me a link otherwise your suggestion will not be taken into consideration

**Comment by Scuffi** [comment]
Here is the plugin link, https://www.spigotmc.org/resources/factionsone.9249/

Sorry.

**Comment by Scuffi** [comment]
Would you be planning on adding this?

**Comment by JCulley** [comment]
I have left it open for now, I currently am rather busy with other obligations so I don't have much time for making additions to the plugin (which is why most was encouraged during the beta). Once I get a chance to look into it we'll see which is why I have left this open. If I do not plan on adding the suggestion I will close the issue.
