### ISSUE TITLE
Mysql Error (2.0.4)

### ISSUE THREAD

**Issue by NeximaOzi** [JCulley/ProQuests-Documentation#103]
I get still same error with latest version.
I can not connect to mysql.
https://hastebin.com/lozadigeka.css

**Comment by JCulley** [comment]
Your MySQL is setup with an encoding which requires too much overhead. If you change your MySQL encoding you won’t have an issue. I had implemented a failsafe which creates the tables using TEXT instead of VARCHAR columns but you still seem to have to much overhead.

Next time when opening an issue please follow the guidelines or you will not receive a response.
