### ISSUE TITLE
Break Quests do not track progress

### ISSUE THREAD

**Issue by Tyloonie** [JCulley/ProQuests-Documentation#116]
Spigot Account: https://www.spigotmc.org/members/tyloonie.130061/

I'm using the latest version of ProQuests, Spigot version CraftBukkit version git-Spigot-b6ecf3b-fb423b8 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT).

My title is pretty selv-explanatory. I've sent a GIF to showcase the issue and attached my quest configuration.

About this specific matter, maybe you could integrate [EzBlocks ](https://www.spigotmc.org/resources/ezblocks.1499/)as a Quest type? That way it would support plugins like TokenEnchant as well.

Showcase: https://gyazo.com/2a23ed6978b3461c554cafa8ac0b62db

[break_1.zip](https://github.com/JCulley/ProQuests-Documentation/files/2000736/break_1.zip)

**Comment by JCulley** [comment]
Please provide more details as “break quests do not track progress” is very vague. I need specifics as to when it doesn’t track, what you even mean by “doesn’t track”. Thanks.

**Comment by JCulley** [comment]
It’s obvious the issue is that whatever plugin you’re using for auto selling the blocks is canceling the event before ProQuests can detect it as a block. So you can contact the owner of the plugin you’re using to hopefully modify the event priority as ProQuests listens on “LOW” priority and will not be changed to “LOWEST” as it has to consider block breaks to be canceled for a number of reasons.
