### ISSUE TITLE
QuestUpdateEvent exception

### ISSUE THREAD

**Issue by Tyloonie** [JCulley/ProQuests-Documentation#124]
Spigot Account: https://www.spigotmc.org/members/tyloonie.130061/

I'm using the latest version of ProQuests, Spigot version CraftBukkit version git-Spigot-b6ecf3b-fb423b8 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT).

Error: https://hastebin.com/enanitozuh.bash

I can try to send more log info, but my log is too long to fit on the usual pasting sites.

**Comment by JCulley** [comment]
Would need more information, this is basically useless to me as I don’t know the context.

**Comment by Tyloonie** [comment]
It still has issues with Buycraft updating. I believe the error from my previous message has to do with Buycraft as well - you have most of the details from my last thread. I believe it's still the same issue: Buycraft updating.

Take a look here: https://hastebin.com/zucekefira.vbs

**Comment by Tyloonie** [comment]
It also sets a mark in the timings: https://gyazo.com/02b5de79d78a3c95a52fa656ad8ac86c (maybe this could be useful)

**Comment by JCulley** [comment]
Can you please provide your entire log file, not just what you deem relevant

**Comment by Tyloonie** [comment]
How do you suggest I send it then? You won't accept .zip files, no online service will accept log files this long - what do I do?

**Comment by Tyloonie** [comment]
Hmmm. I have tried cutting out the important moments that has anything to do with ProQuests, my log is 66k lines.

https://hastebin.com/uwazatokuy.md

**Comment by JCulley** [comment]
> Hmmm. I have tried cutting out the important moments that has anything to do with ProQuests, my log is 66k lines.

Why would you cut out relevant information?

Regardless here's the situation, the only somewhat relevant information you have provided me is this (https://hastebin.com/zucekefira.vbs) which refers to a NullPointerException within the Buycraft Quest code within ProQuests. After investigating it is linked to the portion which compares the start date of the quest and the payment date to ensure the payment was made after the quest was started. The exception being thrown is because the start date is returning null which would not happen at any point unless your quest data had somehow been corrupted. The Buycraft version you are using has been is a newer version than that ProQuests was developed against, so I until it's recompiled against the latest version I cannot determine what bugs my be produced from the version difference. 

> BUYCRAFT version mismatch, ProQuests references version 10.1.1. If you are using the latest version open an issue on GitHub for an updated version! You will not receive support regarding this hook while using a mismatched version

The only rational solution I can provide is to cancel all Buycraft quests and delete any associated data, if this continues to persist with new instances of the quest then feel free to open a new issue.
