### ISSUE TITLE
ProQuest About Repeat Delay

### ISSUE THREAD

**Issue by NeximaOzi** [JCulley/ProQuests-Documentation#125]
Hello,
Spigot name: Nexima
Spigot Account Link: https://www.spigotmc.org/members/nexima.40441/
ProQuest version: Latest
Spigot version: 1.12.2
Log: https://hastebin.com/kalaqoyepo.md

I have big bungeecord server. And i use this plugin in my faction server.
I set "repeat_delay: 86400" (1 day) for all quests.
For example a player get a quest and finish this quest when going to main lobby. Again join to faction server and again can get same quest. So don't wait 1 day.
What can i do for this ?
Thanks for now.
Ozan Seven

**Comment by JCulley** [comment]
Due to the fact I have no knowledge of your setup or how you have configured your quests theres not much I can grasp from this which would help me in any way. If you're using MySQL and have all of your servers connected to the same database then you'll probably need to increase your database delay. Otherwise your log is useless as you have only provided a startup and as far as I can see has nothing related to this issue seems how you didn't give me the log where this actually happened i'm assuming. I'm going to go ahead and close this issue until you can provide sufficient details/information.
