### ISSUE TITLE
DELIVERY_QUEST Error

### ISSUE THREAD

**Issue by hipporunner** [JCulley/ProQuests-Documentation#133]
https://www.spigotmc.org/members/hipporunner.41806/
2.0.4.4
SPIGOT 1.8.8
No Error

DELIVERY_QUEST's are not working when you have more than 1 selected it gives me no error that I can give you so I didnt supply the log file if you need it still please respond saying it I will post asap.

Setup;
I have 1 NPC that opens a diffrent gui with diffrent permissions when players have more than 1 quest selected it wont allow them to turn in the quests after I create 3 DELIVERY_QUEST's for 1 npc.

**Comment by JCulley** [comment]
Ill be completely honest this makes little to sense to me as to what you are even trying to say. As stated in the guidelines you MUST provide a log file. Regardless that wouldn’t help me understand this situation in any way as it sounds more like a specific configuration on your part and doesn’t point to an error in any way. If you can actually provide something that would point to a legitimate error feel free to open a new issue otherwise you should revisit your configuration files.
