### ISSUE TITLE
[SUGGESTION] Ability to grab a player's current active quests and progress via placeholders

### ISSUE THREAD

**Issue by NolanMC** [JCulley/ProQuests-Documentation#138]
This is part of a larger idea I have for my server. Ultimately I want to create an updating scoreboard with Quest progress for the 5 concurrent active quests that a player has active. 

Right now via placeholders, you are able to grab certain statistics for quests with an identifier (ex. %proquests_progress_{identifier}%). I am asking that a system be implemented where I can grab quest information based on the quests that a player has active. Since different players has different quests active, identifiers end up not being too helpful for this usage, especially in my case where I have ~200 quests a player can choose from. They could look something like: 

%proquests_questname_1%
%proquests_questname_2%
%proquests_progress_1%
%proquests_progress_2%
%proquests_total_1%
%proquests_total_2%
The number at the end would represent one of the quests a player has active. If I allow 5 quests, then the placeholders would only work up until 5. Quest names could also refresh and update as they are cancelled, accepted, or completed? 

I am not sure if there is a better way to implement this, and I would love to hear your opinions on that. I have provided a screenshot of what something like this would look like in a scoreboard (not extremely helpful): https://imgur.com/a/MC2hDDM

**Comment by JCulley** [comment]
Interesting concept however this will not be added into the base ProQuests plugin as a feature.  There are too many factors which would have to be considered as to what order to display the quests and which value would assign to one another. The current system is designed using Maps to link the quest data with a unique identifier for the active instance of the quest so you simply cant pull them numerically based on how many the player has active. I would have to implement a system with priorities for each quest type so it knows how to rank them against one another if there are conflicts due to the player having more than the display amount of quests active.

This is a very specific request and I don't see much use by other buyers of the plugin. If this is a vital addition for you I could write a custom add-on plugin for you privately, however it wouldn't be free.  If this is a path you wish to pursue you can add me on Discord CulleyStudios#9786
