### ISSUE TITLE
Plugin Disabling Mid Use

### ISSUE THREAD

**Issue by AtomixCM** [JCulley/ProQuests-Documentation#155]
This feature makes it 10x harder to set your plugin up. Certain plugins create problems when you upload to the latest versions. 

For example, the latest version Worldguard doesn't even work on 1.8 without causing errors.

Tokenenchant causes problems when using the latest version.

Spigot: CM_lectric
Spigot Version: 1.8.8

**Comment by AtomixCM** [comment]
Is this the reason the plugin is randomly disabling itself? I'm in the middle of setting up a quest and then it decides to disable. I really don't understand.

**Comment by JCulley** [comment]
Please keep issues restricted to a specific topic.

In regards to the first statement your stance on this doesn't make much sense. Developers post updates a accommodate new features and to fix existing bugs, I will always update the references once a new version is released and it is requested. 1.8 is over 3 Spigot versions ago, yes ProQuests offers support however I cannot guarantee the support of other 3rd party plugins. You should always be updating your software frequently like anything else.

Please follow the guidelines and provide your entire log file in a pastebin as stated in the guidelines otherwise I can gleam much from the context.

**Comment by AtomixCM** [comment]
I understand having your plugin support the latest versions of plugins if and only if it doesn't cause your plugin to disable.

This paste does nothing but show you that the plugin randomly disabled itself. 
https://hastebin.com/izucexagof.sql

**Comment by AtomixCM** [comment]
I really don't have anything else to report. Can you point me towards something to take a look at to help come up with an explanation?

**Comment by JCulley** [comment]
Who said this had anything to do with the latest versions of dependencies. Please don't make assumptions if you're unsure and let me investigate. You responded less than 5 minutes ago, why are you already posting again? I will be looking into it although you may not think the log is useful it really is. I'm at work right now however ill investigate tonight.

**Comment by JCulley** [comment]
Just looked at the link you provided me, that is not your entire log as requested.

**Comment by AtomixCM** [comment]
Okay hang on

**Comment by AtomixCM** [comment]
https://hastebin.com/vigamobida.pas

I would send you the entire log but it is plagued with spam from a plugin a developer is currently working on.

**Comment by JCulley** [comment]
Using external loaders such as PlugMan will not be supported. Please restart the server and if the error is persistent provide the log from a proper server startup.

**Comment by AtomixCM** [comment]
https://hastebin.com/ehagefumay.sql

**Comment by AtomixCM** [comment]
That is on a fresh load

**Comment by JCulley** [comment]
Thanks, i'll investigate later.

**Comment by JCulley** [comment]
This update should fix the issue, if it doesn't please respond to this issue with an updated server log https://www.spigotmc.org/resources/proquests-1-7-1-12-2-give-players-objectives.18249/update?update=231121
