### ISSUE TITLE
Several suggestions

### ISSUE THREAD

**Issue by RubenBarrionuevo** [JCulley/ProQuests-Documentation#185]
Spigot Username: https://www.spigotmc.org/members/pichurrin.316310/
Spigot Version: 1.12.2
Plugin Version: 2.0.7.1
Description:
Well I think there are certain things that could improve this plugin a lot and that I at least as an administrator will be missing in plugin.
Divide the report into sections, so that your understanding is more fluid

**Suggestion number 1**
I think you could incorporate the possibility of writing any other command or chatting while configuring.
Because, as administrator of a server, dealing with users is totally necessary and must be fluid and comfortable.
It is very tedious to be configuring the mission and not remember what prize you gave as an item from another plugin or which region should develop the mission, and have to stop the creation to consult it.

**Suggestion number 2 - Item of progress**
Honestly I do not know how this option works, I think you should add to tutorials what is their function since I have tried:
In a mission I've done to kill mobs, check the progress with the item that I added and it does not work
![itemprogress](https://user-images.githubusercontent.com/24832320/44407675-050cc800-a55f-11e8-86ec-d21fc1a46959.PNG)
By putting the command / proquest progress modernwar1
I get the following error: You can not cheeck your progress for this quest

yml of the mission: https://pastebin.com/bXpf4vBA
Right now the mission is to kill 50 wither and the progress can not be followed.

**Suggestion number 3. - Cost item and progress**
Just as there is an economic cost to put the mission, there is also an item cost to make missions more cool, (example keys, coins, treasures, among other collectable items for missions)

**Suggestion number 4 - Number of mobs**
If you want to do a mission of mobs, in the last menu there are 3 options (Number of mobs that you must kill, allowed mobs that you can kill and the last one is mobs that you must kill to fulfill the mission or something like that).
If for example in the first option you put 50.
The second option leaves it empty and then the syntax of the third mission tells you:
Type of mobs; value

What do you do ?, you put a number of 50 mobs at the beginning?
Or do you just put at the end withER_SKELETON; 50?

They are undefined that I think would be necessary to define, I also believe that however easy it is to configure missions should be a tutorial on the wiki.
Because for what others are easy, for others it can be more complicated.

I would also save reports, doubts and make things much easier.

My English level is intermediate and to make this suggestion I have used google translate, which translates a bit like the Indians ... so if you do not understand something you just have to consult me and I try to explain it better xD

**Comment by JCulley** [comment]
1. That is not possible in any way seems how the creator relies on chat responses.

2. This makes no sense. It's simple if you don't have the in-hand item in your hand you cannot make any progress towards the quest. If you don't define progress actions then how do you expect it to execute the progress actions?

3. Open an issue with a specific balance type you want added. As I already stated the in-hand item does exactly what you described in the "progress" portion of your statement.

4. The in-game editor is there for a reason, try it out. I don't have time to walk every single person through every single feature which is why I created an intuitive editor in the first place. Regardless not every value is required many are optional.

All in all realistically you stated one "suggestion" which is allowing for chat during creation. As stated this is not possible so I'm closing this issue.

**Comment by RubenBarrionuevo** [comment]
There are many characteristics that are not well defined or there is not enough information about them.

But I see all this empty, it should not be like that ... it's not serious.
https://github.com/JCulley/ProQuests-Documentation/wiki/In-Game-Creator
If you do not have time see adding small parts as you can.

You do not have time to add it, but I do, to try everything?

Thanks for closing the post ahead of time.
