### ISSUE TITLE
Tokenenchant Enchant Registry

### ISSUE THREAD

**Issue by ghost** [JCulley/ProQuests-Documentation#203]
Please have some sort of detector that allows block break requests to count the blocks broken from custom enchantments like explosive or excavation.

Tokenenchant

https://www.spigotmc.org/resources/tokenenchant.2287/updates

These block break enchants only require a player to break one block to trigger the breaking of hundreds or thousands of blocks

**Comment by JCulley** [comment]
So, in short this has nothing to do with the way ProQuests handles anything. The block break quest listens for the Spigot/Bukkit block break event. If whatever external plugins you’re using are not calling the event for each block they remove manually then there’s simply no way for me to track them.

Having said this, they usually avoid doing this for a specific reason and that’s to conserve the server resources. If the event is called 1,000 times that means ProQuests (and whatever other plugins utilizing the block break event such as world guard) would be running 1,000 operations to validate the player and to update their data which as you may imagine is not the most efficient. So in short there’s no feasible way to implement this without a stand-alone TokenEnchant quest with a custom block break event  implemented by TokenEnchant which tracks how many blocks were broken. This would therefore ignore any regular block breaks. If you wish to contact vk2gpz to have him implement this event and reach out to me you can, otherwise there’s not much I can do.

**Comment by ghost** [comment]
EzBlocks tracks the number of blocks broken by tokenenchant enchantments, therefore making this something that ProQuests can potentially do. 

Perhaps you can take a look at the source code of EzBlocks to see how this can be done, because it really isn't resource intensive on my server from the looks of it.

**Comment by JCulley** [comment]
So TokenEnchant has the custom block break event I have previously mentioned it would need to have. As I already mentioned though this would have to be a separate quest as each quest object acts as a listener for one or numerous events, the issue is provided I use the event in the BlockBreak quest if someone is not using TokenEnchant then it would throw a ClassNotFoundException.

**Comment by ghost** [comment]
I see. Can you make a tokenenchant block break quest then? It would be
quite practical I think.

**Comment by JCulley** [comment]
Additionally I would have to do further testing on the system impact as ProQuests has far more checks that need to be done per block broken than a tracker such as EzBlocks has.

**Comment by ghost** [comment]
Okay. Looking forward to the outcome.

**Comment by ghost** [comment]
Hello,
Just bumping this request to see if there have been any advances made.

**Comment by JCulley** [comment]
Just tested it out with the new quest and the performance impact seemed rather minimal being less than 1/10th of a second to perform all quest check operations for 40k blocks (however this was with a skeleton quest with no additional configuration, meaning no other checks such as WorldGuard block/region permissions, allowed worlds etc.)

So I would still advise caution when using this however it has been implemented for the next release.

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-13-1-give-players-objectives.18249/update?update=251793
