### ISSUE TITLE
Error doing /quest leaderboard

### ISSUE THREAD

**Issue by Terrifical** [JCulley/ProQuests-Documentation#219]
**Spigot account** - "Godly"

**Plugin Version**
Provide the ProQuests version you are running (support is only provided for the latest version).
> Example: 2.0.7.1

**Plugin version** - 2.1.1.2

**Spigot Version** - Spigot: 1.12.2 R0.1 SNAPSHOT b1642

**Link to log file** - 

Error: https://pastebin.com/EJjiLS2s
Log: https://hastebin.com/bawuripiso.md

**Additional information** - When doing /quest leaderboard chat message says error check console for the message. (leaderboard won't open) worked on a previous version but updated, haven't change a thing,

**Comment by Terrifical** [comment]
https://www.spigotmc.org/members/godly.227924/

**Comment by JCulley** [comment]
The log you have provided no longer exists, I originally had a look and it was only part of you server startup. I need the entire log from startup to the time the error occurs.

The error paste you have provided is very poorly formatted, please upload it as it is actually outputted line by line because I don't have time to sift through a jumbled mess of text.

Please reply to this issue with the requested information, thanks.

**Comment by Terrifical** [comment]
https://hastebin.com/uyudakakak.md

**Comment by JCulley** [comment]
Is this a single occurrence or is it recurring? Looking at the code there should be no way a null value is passed whatsoever, so I'm curious as to the situation.

**Comment by JCulley** [comment]
Closing as I can’t wait forever for additional information. If this issue reoccurs then open a new issue. However after looking into it that shouldn’t be possible.
