### ISSUE TITLE
Need to improve chat interface for BungeeCord

### ISSUE THREAD

**Issue by 9hrack** [JCulley/ProQuests-Documentation#229]
**Details** 
For BungeeCord servers, the chat interface doesn't work 
because the chat event is not sent to spigot/paper server.

so.. I need a new interface.
some plugins use ANVIL INTERFACE to solve this problem.

I want an option to enable/disable new interface

sorry for my sick english
<br>

**Comment by JCulley** [comment]
You can utilize your own middleware which will call the chat event server side otherwise many chat plugins offer both a proxy and server side component which communicate with one another. The format of quests are dependant on events and as ProQuests is natively a Spigot plugin not a bungee plugin I don’t feel this is a feature worth adding.
