### ISSUE TITLE
Complete Wiki

### ISSUE THREAD

**Issue by Rexmen1** [JCulley/ProQuests-Documentation#232]
Please complete wiki for this plugin. Everything is missing in wiki. If server owners, cant understand how to use plugin, then no one gonna use this plugin. Dont get offended btw this is more of a suggestion+error because me and many other server owners cant use this plugin.

**Comment by JCulley** [comment]
Issues should only be opened for error reporting or feature suggestions, this is neither. There is an extensive in-game creator already provided. I personally have never had the time to document every single feature as due to the vastly customizable nature of the software even if I did document it there would be many caveats with the examples provided not meeting every single buyers specific customization needs. You really need to experiment to see what is possible.
