### ISSUE TITLE
Using unsupported dependency

### ISSUE THREAD

**Issue by Meldiron** [JCulley/ProQuests-Documentation#244]
Error:
[08:18:45 INFO]: [ProQuests] Disabling ProQuests due to a severe dependancy incompatibility.
[08:18:45 INFO]: [ProQuests] Please use the supported dependancy versions for ProQuests.

On spigot it says it supports 1.13, whats the problem?

**Comment by JCulley** [comment]
If you’re going to open an issue you must have actually attempted to solve your own issues in some capacity and follow the guidelines otherwise I will just mark it as I insufficient or just close it. The error message clearly states “dependencies” meaning other plugins in which ProQuests hooks into. Therefore you are using a plugin version which ProQuests does not recognize.
