### ISSUE TITLE
Material Values

### ISSUE THREAD

**Issue by ghost** [JCulley/ProQuests-Documentation#272]
**Spigot account** - https://www.spigotmc.org/members/alex_5678.438771/
<br>

**Plugin version** - 2.1.1.5
<br>

**Spigot Version** - git-Spigot-79a30d7-acbc348 (MC: 1.12.2)
<br>

**Link to log file** - https://pastebin.com/dPfmcR2p
<br>

**Additional information** - Opened the Quest ingame editor changed Allowed Materials to "LOG2;0" and "ACACIA_LOG;0" (wich should be the same; in version 1.12 the first should be right)
Both were accepted but nothing works.

You said "Regardless the quest uses Spigots material names so if you’re using the in-game editor to create the quests it would not allow the material if it does not exist. This means you’re more than likely using an invalid data value." (https://github.com/JCulley/ProQuests-Documentation/issues/251)
How can it be that it checks but accept both an not work anyway with one of them?
<br>

**Comment by JCulley** [comment]
“LOG2” is not a valid material, “ACACIA_LOG” is not a valid 1.12 material. As I already stated this is due to you not configuring it for your according version https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/Material.java?at=refs%2Fheads%2Fversion%2F1.12.2

The material validation (in the creator) was removed due to the incompatibilities between versions and as it is not possible to validate every data value without extensive changes. Overall it would be far to much time to implement when people can simply use the proper materials for their version.
