### ISSUE TITLE
Increasing TOKEN_ENCHANT_BLOCK_BREAK total value

### ISSUE THREAD

**Issue by ghost** [JCulley/ProQuests-Documentation#274]
**Is your feature request a quest suggestion?**
If so please provide a clear explanation of the functionality and the specific requirements you want to be included.

**Details** - {Please increase the maximum total value for TOKEN_ENCHANT_BLOCK_BREAK. It is currently capped at 1,000,000,000. }
<br>

**Does your feature request require another plugin?**
If your request involves another plugin (this includes but is not limited to quests, balance types, teams etc.) you MUST provide a link to the plugin page

**Link to plugin** - {It doesn't require another plugin, I think it just requires a different variable in the code.}
<br>

**Addition Information**
Provide as much additional information explaining the request. This includes but is not limited to images, screenshots, or links to other examples which provide a better understanding The more specific you can be the better as it will help us get a better idea of your vision.

**Additional information** - {Having the token_enchant_block_break value limited to 1 Billion is pretty limiting considering the plugin allows for massive amounts of blocks to be broken. If you could increase the maximum value to go beyond 1.0E9,that would be very helpful.

**Comment by JCulley** [comment]
Will look into it to see how much would need to be changed.

**Comment by ghost** [comment]
I'm guessing that every possible numeric value is capped at 1.0E9, so I should revise this request to be increase the cap of EVERY definable value, not just the token_enchant_block_break quest (Partly because I'm not going to be using the token_enchant_break_quest)

**Comment by JCulley** [comment]
I understand why you would assume that however the true current maximum is that of an Integer because that is how the total is being parsed from the quest YAML file. So the current max is 2,147,483,647.

The NumericQuest object stores all progress and totals in double values (which are significantly larger). It may vary per quest use case in which it is parsed from the YAML file as a double or an int. I designed each of which logically to its use case. For example place, break, kill, etc. are all designed to parse integer values as you cannot have a portion of these ie. you cannot break 1.75 blocks.

If there are specific quests you have a specific use case where it must be larger than the maximum integer value and it currently loads as an integer then open an issue and I will evaluate the suggestion.

**Comment by ghost** [comment]
Does the placeholder_quest allow for a double value? I am going to use the placeholder_quest for blocks broken with EZBlocks for the block break quests once the hooks.yml is readded. I do intend on having the values be above 2.147 Billion, so in this instance I would need a double value.

**Comment by JCulley** [comment]
Please go ahead and do some testing by trying to create a quest with whatever value you may need it set for. If the total is returned as 2,147,483,647 then it is not currently set as such and I ask you please open another issue.

**Comment by ghost** [comment]
I cannot do any testing until the hooks.yml file is readded, otherwise, the map is going to get destroyed.

**Comment by JCulley** [comment]
I don’t understand why you would do your testing on a production server? You can startup a server instance on any machine with Java installed.

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-14-give-players-objectives.18249/update?update=278998
