### ISSUE TITLE
NPC Not Registering

### ISSUE THREAD

**Issue by octobertx** [JCulley/ProQuests-Documentation#309]
**Spigot account** - {https://www.spigotmc.org/members/novisyt.706024/}
<br>

**Plugin version** - {2.1.1.13}
<br>

**Spigot Version** - {git-Spigot-76236cb-9cd1111 (MC: 1.8.8)}
<br>

**Link to log file** - {https://pastebin.com/nL6hVKAB}
<br>

**Additional information** - I am trying to set a Start NPC and End NPC for a quest I have created. I am successfully creating the ProQuest NPC (https://gyazo.com/99c3487d2e20d055880e2c3a66c42f98) But when I try to set the start or end NPC, it says it's not a registered NPC (https://gyazo.com/dee700af2555d4a8bcb12b42815dfd3f).
<br>

**Additional media** - Sorry for the low mic audio, the level was low on OBS. https://youtu.be/8r_UbGwHzzQ
<br>

**Comment by JCulley** [comment]
Please try the following before I engage further to see if there are actually any issues internally:

1. Remove the random [StartQuest] action you entered, it's not needed.
2. Attempt a /proquests reload before attempting to link the NPC to the quest
3. Edit the NPC and remove the Citizen section, then attempt to link it

If it still doesn't work after all of this send me the YAML configurations for the quest and the npc, otherwise it's rather difficult for me to investigate.

**Comment by octobertx** [comment]
[New folder (2).zip](https://github.com/JCulley/ProQuests-Documentation/files/3372934/New.folder.2.zip)

**Comment by JCulley** [comment]
As stated I will not download any files, you can use a site such as pastebin. Additionally did you even try the steps I suggested? I'm not going to waste my time without more information.

**Comment by octobertx** [comment]
I did try your steps and it unfortunately didn't fix my issue. Here are the pastebins:
(P.S. After going through the NPC and Quest YMLs, they are blank even after creating the npc and quest multiple times)

Quest YML: https://pastebin.com/AB9MYNKW
NPC YML: https://pastebin.com/1qD4fkw0

**Comment by JCulley** [comment]
Unless you’ve changed the config.yml they’re in the folders, I wouldn’t know as I wasn’t provided that either.

**Comment by octobertx** [comment]
Sorry, my first time using proquests or github.

https://pastebin.com/9WeE9P1C

Contains the config, npc and quest yml

**Comment by JCulley** [comment]
There’s still a citizen linked in what you have provided me, I thought you had followed the steps I had stated?

**Comment by octobertx** [comment]
Hmm that's odd, I had removed the citizens. I'm going to delete the YML and try again.

**Comment by octobertx** [comment]
# ======================================================
# 
# ProQuests Version: 2.1.1.13 build: 706024
# Created by: JC_Plays_MC
# 
# ======================================================

npc_type: QUEST
author: 936c321d-b169-4841-8e90-b44dee548c28
editable: true
entity_type: PLAYER
name: David Leatherman
location: main,202.4173,53.0000,1295.3000
linked_quests:
- David


Here is the new NPC yml, problem is still happening. If you don't know why this is happening, I will just have a custom quests plugin made, it's not that big of a deal.

**Comment by JCulley** [comment]
Can you provide the log when you restarted your server with the NPC without the Citizens section. If you don’t provide as much information as possible it’s kind of impossible for me to know why this is happening. Best guess is that it’s never even being loaded which would be clearly stated in the log file, however the only one I have is from 3 days ago which clearly stated “Unable to locate any npcs to load...”.

So from all of the information I’ve received I’m lead to believe it was never loaded to begin with which is why the quest obviously cannot locate it.

**Comment by octobertx** [comment]
https://pastebin.com/kxTLSW65

**Comment by JCulley** [comment]
> 09.07 09:30:12 [Server] INFO Succesfully loaded the 'David' NPC

Did you even look at it yourself or just send it? As can be seen it’s loaded, so go ahead and try now.

P.S - In the future I will not be trying this hard to get information from you, if you’re not willing to put in some effort looking into the “problem” yourself I will simply close the issue. I don’t have time to do this constant back and forth.

**Comment by octobertx** [comment]
issue still persists even with it loading correctly. doesnt look like its gonna work. thanks for the help anyways.
