### ISSUE TITLE
Suggestion for minigblock (reupload)

### ISSUE THREAD

**Issue by MrBaguette07** [JCulley/ProQuests-Documentation#313]
**Details** - I am sorry, I am sorry.

I'll explain better, on my network, I have a mine, on this mine I put a protection worldguard in "block-break: deny" and I use the plugin "miningblocks" to be able to break. This plugin passes over the worldguard protection when disabled in configuration.
What I'm asking you to add when you're out of the box

because they only have the operator when they are mine and not the players.

(I'm sorry for the mistakes I'm french)
<br>

**Link to plugin** - https://www.spigotmc.org/resources/miningblocks-1-8-1-14.6438/
<br>

**Additional information** - I explained everything above.

**Comment by JCulley** [comment]
This still doesn’t make any sense. If you don’t want ProQuests to hook into WorldGuard then disable it from the hooks.yml file. If you don’t want to disable the hook then properly define your regions the way WorldGuard intends rather than bypassing existing flags by modifying the event earlier with other plugins.
