### ISSUE TITLE
[Suggestion] Add Advancements for 1.12 and UP

### ISSUE THREAD

**Issue by maxlehot1234** [JCulley/ProQuests-Documentation#62]
Hi, I just want to know if you can add support for Advancements for minecraft 1.12

It could be really nice to see everything inside the advancements TAB ;)

Maybe by using this API:
https://www.spigotmc.org/resources/crazy-advancements-api.51741/
OR this one:
https://www.spigotmc.org/threads/advancementapi-create-1-12-advancements.240462/

With it we can create an AMAZING advancements trees :)

Hope you can add it in a future updates ;)

No one suggest it I think so I do it

Thanks again, since I have not a lof things to say except this

**Comment by JCulley** [comment]
Hey,

I have considered adding this and originally it was going to be apart of the v2.0 update however most buyers don't use a new enough version which would support this feature so I decided against it. Personally if I plan on adding this it will be in the form of an expansion due to the complexity of adding it and the small pool of users who would actually utilize the feature.

Best Regards.

**Comment by maxlehot1234** [comment]
If you can create it I will buy it if it was a premium ressource for sure :)


Since it will be a really nice thing to have ;)

Thanks for your reply and hope you will develop this

lundi 8 janvier 2018 21:29 -0500 de notifications@github.com  <notifications@github.com>:
